type Review {
  id: ID
  author: User
  feedback: String
  rate: Float
  propriety: Propriety
}

type Query {
  reviewByUser(id: ID): [Review]
}

input inputReviewType {
  authorId: ID
  feedback: String
  rate: Float
  proprietyId: ID
}

type Mutation {
  addReview(body: inputReviewType): Review
}
