import type { NextPage } from 'next';

import { useEffect } from 'react';
import axios from 'axios';
import Head from 'next/head';
import Image from 'next/image';

import styles from '@/styles/Home.module.css';

import { ColorType, SpotsType, MushroomType } from '@/types/mushroom';
import useOnFetch, { promiseReuslt } from '@/hooks/useOnFetch';

const Home: NextPage = () => {
  async function fetchMyAPI(): Promise<
    promiseReuslt<MushroomType[]>
  > {
    try {
      const { data } = await axios.get('/api/mushroom');

      return data;
    } catch (error) {
      return { result: null, success: false };
    }
  }
  const { onFetch, result, isSuccess, isLoading } =
    useOnFetch<MushroomType[]>();

  useEffect(() => {
    onFetch(fetchMyAPI);
  }, []);
  useEffect(() => {
    console.log(
      '🚀 ~ file: index.tsx ~ line 14 ~ useEffect ~ data',
      result,
    );
  }, [result]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>here main page</h1>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image
              src="/vercel.svg"
              alt="Vercel Logo"
              width={72}
              height={16}
            />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
